name: KWEATHER_API

on:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean package

      # Send the WAR file via SCP
      - name: Copy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          source: ./target/kweather-api.war
          target: /home/admin/deploy

      # Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          script: |
            conda deactivate
            cd /home/admin/deploy
            if [ `ps -ef | grep -v grep | grep -c "java -jar kweather-api.war"` != 0 ]; then
              kill -9 `ps -ef | grep -v grep | grep "java -jar kweather-api.war" | awk '{print $2}'`
            fi
            rm -f kweather-api.war
            mv ./target/kweather-api.war .
            rm -rf ./target
            chmod +x kweather-api.war
            java -jar kweather-api.war >> kweather-api.log &
